# User
WELCOME_MAIL = "WELCOME_MAIL"
PASSWORD_RESET = "PASSWORD_RESET"
NEW_FOLLOWER = "NEW_FOLLOWER"
USER_INVITE = "USER_INVITE"
EMAIL_VERIFICATION = "EMAIL_VERIFICATION"


# MAP OF NOTIFICATION TYPES TO SETTINGS
NOTIFICATION_TYPE_SETTINGS_MAP = {}
